# Generated by Django 6.0.1 on 2026-01-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('cia_type', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
