# Generated by Django 6.0.1 on 2026-03-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classroommembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.classroom'),
        ),
    ]
