# Generated by Django 6.0.1 on 2026-03-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subject_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='section',
        ),
    ]
