# Generated by Django 6.0.1 on 2026-03-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_subject_assignment_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_grade',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
