# Generated by Django 6.0.1 on 2026-03-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_max_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
