# Generated by Django 6.0.1 on 2026-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
